name: sitemap-downloader
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - requests>=2.31.0
  - lxml>=4.9.0
  - pip>=23.0.0
  - regex>=2023.0.0
  - urllib3>=2.0.0
  - certifi>=2023.7.22
  - charset-normalizer>=3.0.0
  - idna>=3.4
  # Development tools (optional)
  - ipython
  - jupyter
  - pytest
pip:
  - beautifulsoup4>=4.12.0  # For additional HTML parsing if needed